### PR TITLE
Add support for Picture element

### PR DESCRIPTION
**Pull request by IgorUsoltsev**
Added support for Picture element for this brilliant plugin. 

NOTE: your <picture> element is required to have at least 1 `` (it is the only valid markup for this element but still)

### CODE REVIEW

**Comment by briangonzalez** [comment]
@IgorUsoltsev Mind adding in a demo?

https://github.com/briangonzalez/jquery.adaptive-backgrounds.js/tree/master/demos

**Comment by briangonzalez** [comment]
Oh, and thanks for the PR!

**Comment by IgorUsoltsev** [comment]
Hey, sure, feel free to use

Glad it will help someone

**Comment by briangonzalez** [comment]
Would you be willing to create a demo @IgorUsoltsev ?

**Comment by IgorUsoltsev** [comment]
Ah sorry, didn't get you. Np will make in few days

**Comment by IgorUsoltsev** [comment]
Hey @briangonzalez 

Just pushed the demo

**Comment by AlfredJKwack** [comment]
Hi,

Testing this out I note there are some browser support issues on Chrome (v58 on MacOS). 

Since the current demo didn't entirely mimic the spec, I made some changes to it. According to [the spec](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture), multiple source elements (with appropriate media attributes) are allowed for a single image element.

Assume the below change to the demo and a window size larger than 600px. 

```
  <div class='img-wrap'>
      <picture id="img" data-adaptive-background>
          <source srcset="images/2.jpg" media="(max-width: 599px)">
          <source srcset="images/3.jpg" media="(min-width: 600px)">
          <img src="images/1.jpg">
      </picture>
  </div>
```
The resulting image looks like the below. As you can see, it takes the background color from 1.jpg while what's being displayed is 3.jpg. This is not what one would expect. 

When I reload the page several times with one or multiple images I get different results which indicates inconsistency in Chrome. Testing this out in Safari however posed no such problems and it ran as designed.

@briangonzalez Appreciate your thoughts. As far as I can tell the code is not at issue here.

scap

**Comment by AlfredJKwack** [comment]
Digging a little further I found that the [Chrome team decided](https://bugs.chromium.org/p/chromium/issues/detail?id=378188#) to:

> Update currentSrc just before HTMLImageElement.onload
> During the spec discussions [1], we have come to the conclusion that currentSrc
> should be updated only before onload/onerror are triggered.
> This CL implements that behavior.

I've also made a quick [CodePen to illustrate](https://codepen.io/anon/pen/BZNmBw?editors=1011) behaviour differences between browsers. Pulling up the console in Chrome I see that sometimes the second log call comes up with an empty string, sometimes not...

My conclusion here would be that the code is probably fine but we be clear that an appropriate tigger point (ie. the difference between `window.onload` vs `$(document).ready()` )  can be key to how things can be expected to behave.

scrap

**Comment by briangonzalez** [comment]
@AlfredJKwack This diff is quite small and comes with a demo. I am cool shipping it.

Thanks for all of your hard work.

**Pull request merged**
