### PR TITLE
Shade variation

### PR DESCRIPTION
**Pull request by DigitalKrony**
Ability to adjust the shade of the color based on a % or a blend of a desired color variable. Works in both +/- for light and dark colors.

### CODE REVIEW

**Comment by AlfredJKwack** [comment]
Hi, 

@briangonzalez Do you have an issue with the feature itself? I'd be open to review this but the current PR is a little daunting as it has far too many lines vs actual changes and conflicts with the current code base. From what I can tell it should not conflict with the existing implementations and thus be transparent for anyone pulling an update.

@DigitalKrony Without presuming on Brian's answer, the approach I would take is for you to pull a more recent build and submit a new PR with just the changes. As it stands now there's conflicts and quite a bit of extraneous stuff.

From a quick scan of the code I would expect to see just changes at:
- The DEFAULTS, where you add 3 new properties: shadeVariation, shadePercentage, shadeColors
- The new function shadeRGBColor(color, percent)
- The new function blendRGBColors(c0, c1, p)
- The new function shadeAdjustment(color)
- The implementation through the if( opts.shadeVariation != false ) {} function.

A clear explanation of shadeRGBColor and blendRGBColors would also help the review as they're a little terse.

Beyond this I really appreciate that you did post a demo.

Once reviewed and accepted by @briangonzalez we'll need to make sure it's documented in the README.md file.

Rgds,
AJK

**Comment by DigitalKrony** [comment]
Well. Cool. Glad you took a look.

It's been sitting around for two years so I would imagine that there'd be some conflicts. I'm booked with work but when I have an opportunity to re-sync with things I'll take a peek and try to remember where I was, though process wise, when I wrote this up.

Watch for my commit.

**Comment by AlfredJKwack** [comment]
Will do. Thanks for sticking around.

**Comment by briangonzalez** [comment]
I really like this from a high level. This repo has sort of fallen on disrepair. I am revamping all of my open source projects right now, and this one is top of the list.

With that said, @AlfredJKwack, I trust you to administer changes like this in the interim.

@DigitalKrony – I am very sorry for letting this slip for 2 years! That's my bad. Thank you for the PR.

**Comment by briangonzalez** [comment]
@AlfredJKwack What do you think? Shall we?

**Comment by DigitalKrony** [comment]
Spaces updates.

**Pull request merged**
